# Usa la imagen base oficial de NGINX desde Docker Hub
FROM nginx:latest

# Copia el archivo de configuración personalizado de NGINX al contenedor
COPY nginx.conf /etc/nginx/nginx.conf

# Copia el contenido estático al directorio predeterminado de NGINX
COPY html /usr/share/nginx/html

# Expone el puerto 80 para el contenedor
EXPOSE 8000

# Comando por defecto para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]