
name: main

on:
  push:
    branches: 
      - master
    paths:
      - 'apps/docs/**'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: hello world
        run: echo "hello from docs"
